### ISSUE TITLE
Turning proofs into rules

### ISSUE THREAD

**Issue by nomeata** [nomeata/incredible#11]
It should be possible to 
 * Chose to start without a task
 * Have the logic core return to the UI the `rule` that the current graph would prove to be valid, if the graph has no errors.
 * Have a button to save the current graph as a rule, which is then added to the logic.

This would allow the user to define his own block for “(¬P ⇒ ⊥) ⇒ P".

**Comment by nomeata** [comment]
See branch ruleexport.

**Comment by gattschardo** [comment]
I tried to implement the relabeling of ports, see bf910ee9d8, unfortunately it does not work as intended. My strategy is as follows:

For each block that has surface contact (i.e. an open port that needs to become part of the exported rule),
collect the connection-labels of all its non-open ports and unify these propositions with the port-propositions. My understanding was that this should result in a unification of the block variables with the terms that represent them in the connected propositions.
The next step is to apply the resulting binding to the props of the open ports. (Last step is, still, to take the renamed block variables into account into account, but I did not begin implementing this yet).

The problem is that this does not work. I think in principle this approach should work, so I assume I have used the unification improperly. (Also I need the free variables that occur in the already unified connection labels, my code to collect them is incomplete and generally terrible, so this may be an issue)

Any ideas?

**Comment by nomeata** [comment]
Far too complicated. You simply need the [`final_bind`](https://github.com/nomeata/incredible/blob/bf910ee9d88059b42c05e3d9552669d50cfcfe7f/logic/LabelConnections.hs#L99) from `LabelConnections.hs`: This is the instantiation you can apply to the proposition at the port (well, to the renamed port), similar to how it is done in `LabelConnections`.

You will enventually, also need to know what variables are free and what not in the resulting terms, and also whether any of these are scoped.

So I think you will have to refactor the code, and pull a lot of `LabelConnections` out into a module, say `Analysis`, that returns things like `final_bind`, `scopeMap`, maybe parts of `renamedBlockData`, and then use this data both in `labelConnections` and your code.

**Comment by gattschardo** [comment]
This does sound like a better approach, I will try to implement that.

One question though: I think this new `Analysis` should be executed only once, in `Entry` and the result passed on to `LabelConnections` and `Rules` to further obtain the relevant data. Would you agree with that? Or would you prefer to have the `Analysis` to be (potentially) be calculated multiple times, but not be visible/called in `Entry`?

**Comment by nomeata** [comment]
>  Would you agree with that?
Yes!

**Comment by nomeata** [comment]
Also note that not every proof can be turned into a rule, as the rule format only allows a certain form of assumptions: Formally, only those of type

  ∀x. ((∀y.(H₁₁(x,y)∧H₁₂(x,y)… )→A₁(x,y)) ∧ (∀y.(H₂₁(x,y)∧H₂₂(x,y)… )→A₂(x,y)) ∧ …) → (C₁(x)∧C₂(x)∧…)

where x and y can be a number of variables, and the *A*ssumptions may of course have zero local *H*ypothesis, and where ∀, ∧ and → are on the meta-logic level.

**Comment by mohrm** [comment]
Now it compiles on my machine with GHC 7.8.4.
But if I just click on "start empty proof" the javascript code immediately crashes and the logic does nothing anymore.
A bit debugging shows that the function renderDesc (shapes.js:72ff) does not handle the case that desc = {}, which is the case when starting with an empty proof and an empty block.
Replacing the "throw new Error" with
text = V("<text class='label center' font-family='sans' fill='black'/>");
    text.text("42");
makes the code work again and shows a "You proved: <block 42>"
I think this bug was introduced when @nomeata rewrote the rendering part without having in mind that the block to render may be empty...

**Comment by mohrm** [comment]
Other than that, the rule inference still does not seem to do much useful stuff:
When I just plug two intro-∧ blocks together, I would expect to have proven a rule with A, B and C as inputs and A∧B∧C as one single output.
Instead I get A, B and B [sic!] as input and A∧B as output.

Are my expectations that wrong or does the code not do what we want yet, @gattschardo @nomeata ?

**Comment by nomeata** [comment]
Thanks for the analysis, fixed in e5e5026.

**Comment by nomeata** [comment]
> Are my expectations that wrong or does the code not do what we want yet, @gattschardo @nomeata ?

It is still wip, I think Richard is aware of that.

**Comment by gattschardo** [comment]
Yes, I am aware! One other thing though: I tried to fix all the example-tests by adding a `rule: null` field to the expected output (see 0e59a8b), but the tests still fail. Apparently the slightly altered unification and labelling process gives different indices to the variables, so `c₇` becomes `c₈` in `nex2alln` and similar things in other tests.
I will refrain from renaming them all for now, because as I work the numbering might change again. Or we could change the test runner to be able to identify such identities (?)

**Comment by nomeata** [comment]
It should be more stable now since 2d47e3a, since the numbers are now based on the input (at least unless fresh unification variabls pop up), so I’d say you can update the output.

Also, `cabal run update-tests` will do that for you; just make sure you review the diff before committing.

**Comment by mohrm** [comment]
looks nice!

one thing that bothers me: Shouldn't local hypotheses be treated differently from real inputs? If I just put an impI block there, the incredible proof machine tells me that I have just proved a rule where I just have to put in some statement B₂ and I get an arbitrary statement A₂ for free. At least it looks that way. Could be a UI thing, though - the details tell me that A₂ can only be consumed by the input.

**Comment by mohrm** [comment]
Still, there should be a possibility to kill unused local hyptotheses to prevent them from appearing in the outputs of an inferred rule...

**Comment by nomeata** [comment]
> Still, there should be a possibility to kill unused local hyptotheses to prevent them from appearing in the outputs of an inferred rule...

For that, a block with an assumption `P` and no conclusion could be used: This way, the local assumption would no longer be unconnected.

**Comment by nomeata** [comment]
Richard and me just did some more hacking on this, fixed stupid bugs by me in the JSON serialization and got the scoped variables hopefully right.

What’s missing:

 * Identify local hypotheses and set the right `consumedBy`. Local hypotheses are output ports that are forward-reachable from a local hypotheses (without passing through the `consumedBy` port). The corresponding port is the (a) port that is backwards-reachable from the `consumedBy` port of the port we started with. All clear?
 * Make sure all names are exportable, i.e. pass them through `\n -> makeName (name2String n) 0`, but without causing collisions.

We’re getting there... eventually.

**Comment by nomeata** [comment]
It would be nice to get the branch closer to master, so that I can refactor things without causing horrendous merge problems. Maybe we can fix the second issue, and solve the first one by (for now) simply not producing rules where there are local hypotheses involved. It will not be very useful, but would allow it to enter master, and you can improve the feature without having such a long-lived separate branch.

Also, I’d like to change the UI so that custom blocks are created by selecting blocks from an existing proof. This would change the interface: There’d be a separate call to the logic that gets just the selected part of the proof, and should just remove the generated rule
